import XCTest
@testable import DatedImageGeneratorLib

final class DatedImageGeneratorTests: XCTestCase {
    
    var pathToTestAssetCatalog: String {
        let currentFilePath = #filePath
        let folder = (currentFilePath as NSString).deletingLastPathComponent
        let pathToCatalog = (folder as NSString).appendingPathComponent("Media.xcassets")
        return pathToCatalog
    }
    
    func testGettingNamesOfImageSets() throws {
        let names = try DatedImageGeneratorLib.imageNamesForCatalog(at: self.pathToTestAssetCatalog)
        
        XCTAssertEqual(names.sorted(), [
            "hank_case",
            "klausje",
        ])
    }
    
    func testContentForCatalog() throws {
        let content = try DatedImageGeneratorLib.fileContent(for: [self.pathToTestAssetCatalog])
        
        XCTAssertEqual(content,
"""
/// This file auto-generated by Dated Image Generator. Do not edit manually.

struct AssetCatalogImages {
  static let hank_case = DatedImage(imageName: "hank_case", dateTaken: Date)

  static let klausje = DatedImage(imageName: "klausje", dateTaken: Date)
}
""")
    }
}
